apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80           # Expose port 80 on the external world
      targetPort: 5000    # Flask application is running on port 5000 inside the container
  type: NodePort      # This will create a LoadBalancer for external access

